# Generated by Django 4.2.6 on 2023-10-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
