# Generated by Django 4.2.6 on 2023-10-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_newsletter_newsletter_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter_list',
            new_name='Subscriber',
        ),
    ]
